title: Your Portfolio Title
description: Your portfolio description
remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme

# Add navigation links
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Projects"
    url: "/projects/"
  - title: "Blog"
    url: "/blog/"
  - title: "Contact"
    url: "/contact/"
